export const TEST = 'TEST';

export const CHANGE_HEMATOLOGY = 'CHANGE_HEMATOLOGY';
export const CHANGE_PATHOLOGY = 'CHANGE_PATHOLOGY';
export const CHANGE_MICROBIOLOGY = 'CHANGE_MICROBIOLOGY';
export const CHANGE_RADIOLOGY = 'CHANGE_RADIOLOGY';
export const CHANGE_PATIENT_INFO = 'CHANGE_PATIENT_INFO';
export const RESET_FORM = 'RESET_FORM';

export const UPDATE_PENDING_LIST = 'UPDATE_PENDING_LIST';
export const START_LOADING_LAB_LIST = 'START_LOADING_LAB_LIST'
export const STOP_LOADING_LAB_LIST = 'STOP_LOADING_LAB_LIST'

export const START_LOADING_LAB_HISTORY = 'START_LOADING_LAB_HISTORY'
export const STOP_LOADING_LAB_HISTORY = 'STOP_LOADING_LAB_HISTORY'
export const UPDATE_LAB_HISTORY = 'UPDATE_LAB_HISTORY';
